### PR TITLE
Add missing uni_vmovdqu operation overload for AVX-512

### PR DESCRIPTION
**Pull request by avoskoboinyk-lohika**
# Description

This change unbreak uni_vmovdqu() function resolution for reg <- reg scheme on AVX-512.
Other overloads have only reg <- addr and addr <- reg schemes plus one for xmm <- xmm register move - but, for the last, operation is invalid for AVX-512.
Add special overload for zmm registers to resolve 'invalid instruction' errors in runtime.

The test case was attached to Interpolate-4 PR: https://github.com/openvinotoolkit/openvino/pull/12771/commits/42136687262aa78834ce8dcdd20c67f207be7d42

While here, add VEX / non-VEX switch functions for vpblendw and vucomiss instructions into jit_generator component - they are required too for Interpolate-4 PR.

OpenVINO PR:
- https://github.com/openvinotoolkit/openvino/pull/12771

### CODE REVIEW

**Comment by avoskoboinyk-lohika** [comment]
This PR is needed for https://github.com/openvinotoolkit/openvino/pull/12771

**Review by lohika-denis-kotov — APPROVED** [review]
LGTM

**Comment by dmitry-gorokhov** [comment]
Approved

**Comment by avoskoboinyk-lohika** [comment]
This one was merged into the Interpolate-4 kernel and should be merged into jit_base when the kernel will be rebased onto jit_kernel base class.
The PR is obsolete; closing.

**Pull request closed without merging**
